//
//  AuthRouter.swift
//  NimbleTest
//
//  Created by master on 10/4/17.
//  Copyright (c) 2017 neemo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AuthRoutingLogic
{
  func routeToMainScreen()
  func routeToAuthScreen()
}

protocol AuthDataPassing
{
  var dataStore: AuthenticateDataStore? { get }
}

class AuthRouter: NSObject, AuthRoutingLogic, AuthDataPassing
{
   
    
  weak var viewController: ViewController?
  var dataStore: AuthenticateDataStore?
  
  // MARK: Routing
  
  func routeToMainScreen()
  {
    //viewController?.showMainScreen(response: <#T##Auth.Login.Response#>)
  }
    
    func routeToAuthScreen()
    {
        //viewController?.showAuthScreen()
    }
  
    //MARK: Passing data
    
   
    


  // MARK: Navigation
  
  //func navigateToSomewhere(source: AuthViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
 
}
