//
//  ListSurveyModelsModels.swift
//  Nimble
//
//  Created by master on 10/4/17.
//  Copyright (c) 2017 neemo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListSurvey
{
  // MARK: Use cases
  
  enum FetchSurvey
  {
    struct Request
    {
        var credentialKey : String = "access_token"
        var accessToken   : String = ""
        
        func getParams() -> Dictionary<String , String>
        {
            return [credentialKey : accessToken]
        }
    }
    struct Response
    {
        var surveyModel : [SurveyModel]
    }
    struct ViewModel
    {
        struct DisplayedSurvey
        {
            var title               : String
            var description         : String
            var backrgroundImageUrl : String
            
        }
        var displayedSurveys: [DisplayedSurvey]
    }
  }
}
