//
//  ListSurveyInteractor.swift
//  Nimble
//
//  Created by master on 10/3/17.
//  Copyright (c) 2017 neemo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListSurveyBusinessLogic
{
    func fetchSurveysFromRemote(request :ListSurvey.FetchSurvey.Request)
}

protocol ListSurveyDataStore
{
   var surveys: [SurveyModel]! { get }
}

class ListSurveyInteractor: ListSurveyBusinessLogic, ListSurveyDataStore
{
    var surveys: [SurveyModel]!
    var presenter: ListSurveyPresentationLogic?
    var worker = ListSurveyWorker(store : SurveyAPIStore())
  
  func fetchSurveysFromRemote(request: ListSurvey.FetchSurvey.Request)
  {
    
    worker.fetchSurvey(request: request, completionHandler: {(surveys : [SurveyModel]) in
        self.surveys      =   surveys
        let response = ListSurvey.FetchSurvey.Response(surveyModel: self.surveys)
        self.presenter?.presentSurveys(response: response)
    })
  }
}
